# Generated by Django 2.1 on 2024-06-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_routers'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktops',
            name='employee',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptops',
            name='employee',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobiles',
            name='employee',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printers',
            name='employee',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routers',
            name='employee',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
