# Generated by Django 2.1 on 2024-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20240625_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktops',
            name='department',
            field=models.CharField(default='IT', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptops',
            name='department',
            field=models.CharField(default='MAINTENANCE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobiles',
            name='department',
            field=models.CharField(default='QUALITY', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printers',
            name='department',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routers',
            name='department',
            field=models.CharField(default='PAINT SHOP', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='desktops',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in few days'), ('NOT AVAILABLE', 'Item currently not available')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in few days'), ('NOT AVAILABLE', 'Item currently not available')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in few days'), ('NOT AVAILABLE', 'Item currently not available')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='printers',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in few days'), ('NOT AVAILABLE', 'Item currently not available')], default='SOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='routers',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item already purchased'), ('RESTOCKING', 'Item restocking in few days'), ('NOT AVAILABLE', 'Item currently not available')], default='SOLD', max_length=10),
        ),
    ]
