# Generated by Django 2.1 on 2024-06-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20240625_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktops',
            old_name='employee',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='employee',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='employee',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='printers',
            old_name='employee',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='routers',
            old_name='employee',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='desktops',
            name='department',
            field=models.CharField(choices=[('QUALITY', 'Quality'), ('MAINTENANCE', 'Maintenance'), ('MEP', 'MEP'), ('PROJECTS_CENTER_SERVICES', 'Projects & Center Services'), ('SAFETY', 'Safety'), ('PROGRAM_MANAGEMENT', 'Program Management'), ('FABRICATIONS_OPERATIONS', 'Fabrications Operations'), ('RECEPTIONS', 'Receptions'), ('COMPLIANCE_TEAM', 'Compliance Team'), ('HUMAN_RESOURCE', 'Human Resource'), ('CENTRAL_PURCHASE', 'Central Purchase'), ('FINANCE', 'Finance'), ('NPP', 'NPP'), ('PRODUCTION_ENGINEERING', 'Production Engineering'), ('DESIGN_CENTER', 'Design Center'), ('SERVICE_TEAM', 'Service Team'), ('IT', 'IT'), ('NETWORK', 'Network')], max_length=200),
        ),
        migrations.AlterField(
            model_name='laptops',
            name='department',
            field=models.CharField(choices=[('QUALITY', 'Quality'), ('MAINTENANCE', 'Maintenance'), ('MEP', 'MEP'), ('PROJECTS_CENTER_SERVICES', 'Projects & Center Services'), ('SAFETY', 'Safety'), ('PROGRAM_MANAGEMENT', 'Program Management'), ('FABRICATIONS_OPERATIONS', 'Fabrications Operations'), ('RECEPTIONS', 'Receptions'), ('COMPLIANCE_TEAM', 'Compliance Team'), ('HUMAN_RESOURCE', 'Human Resource'), ('CENTRAL_PURCHASE', 'Central Purchase'), ('FINANCE', 'Finance'), ('NPP', 'NPP'), ('PRODUCTION_ENGINEERING', 'Production Engineering'), ('DESIGN_CENTER', 'Design Center'), ('SERVICE_TEAM', 'Service Team'), ('IT', 'IT'), ('NETWORK', 'Network')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mobiles',
            name='department',
            field=models.CharField(choices=[('QUALITY', 'Quality'), ('MAINTENANCE', 'Maintenance'), ('MEP', 'MEP'), ('PROJECTS_CENTER_SERVICES', 'Projects & Center Services'), ('SAFETY', 'Safety'), ('PROGRAM_MANAGEMENT', 'Program Management'), ('FABRICATIONS_OPERATIONS', 'Fabrications Operations'), ('RECEPTIONS', 'Receptions'), ('COMPLIANCE_TEAM', 'Compliance Team'), ('HUMAN_RESOURCE', 'Human Resource'), ('CENTRAL_PURCHASE', 'Central Purchase'), ('FINANCE', 'Finance'), ('NPP', 'NPP'), ('PRODUCTION_ENGINEERING', 'Production Engineering'), ('DESIGN_CENTER', 'Design Center'), ('SERVICE_TEAM', 'Service Team'), ('IT', 'IT'), ('NETWORK', 'Network')], max_length=200),
        ),
        migrations.AlterField(
            model_name='printers',
            name='department',
            field=models.CharField(choices=[('QUALITY', 'Quality'), ('MAINTENANCE', 'Maintenance'), ('MEP', 'MEP'), ('PROJECTS_CENTER_SERVICES', 'Projects & Center Services'), ('SAFETY', 'Safety'), ('PROGRAM_MANAGEMENT', 'Program Management'), ('FABRICATIONS_OPERATIONS', 'Fabrications Operations'), ('RECEPTIONS', 'Receptions'), ('COMPLIANCE_TEAM', 'Compliance Team'), ('HUMAN_RESOURCE', 'Human Resource'), ('CENTRAL_PURCHASE', 'Central Purchase'), ('FINANCE', 'Finance'), ('NPP', 'NPP'), ('PRODUCTION_ENGINEERING', 'Production Engineering'), ('DESIGN_CENTER', 'Design Center'), ('SERVICE_TEAM', 'Service Team'), ('IT', 'IT'), ('NETWORK', 'Network')], max_length=200),
        ),
        migrations.AlterField(
            model_name='routers',
            name='department',
            field=models.CharField(choices=[('QUALITY', 'Quality'), ('MAINTENANCE', 'Maintenance'), ('MEP', 'MEP'), ('PROJECTS_CENTER_SERVICES', 'Projects & Center Services'), ('SAFETY', 'Safety'), ('PROGRAM_MANAGEMENT', 'Program Management'), ('FABRICATIONS_OPERATIONS', 'Fabrications Operations'), ('RECEPTIONS', 'Receptions'), ('COMPLIANCE_TEAM', 'Compliance Team'), ('HUMAN_RESOURCE', 'Human Resource'), ('CENTRAL_PURCHASE', 'Central Purchase'), ('FINANCE', 'Finance'), ('NPP', 'NPP'), ('PRODUCTION_ENGINEERING', 'Production Engineering'), ('DESIGN_CENTER', 'Design Center'), ('SERVICE_TEAM', 'Service Team'), ('IT', 'IT'), ('NETWORK', 'Network')], max_length=200),
        ),
    ]
