# Generated by Django 2.1 on 2024-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20240626_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktops',
            name='date',
            field=models.DateField(default='2024-07-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptops',
            name='date',
            field=models.DateField(default='2024-07-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobiles',
            name='date',
            field=models.DateField(default='2024-07-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printers',
            name='date',
            field=models.DateField(default='2024-07-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routers',
            name='date',
            field=models.DateField(default='2024-07-04'),
            preserve_default=False,
        ),
    ]
