# Generated by Django 2.1 on 2024-07-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20240704_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktops',
            name='date',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='date',
        ),
        migrations.RemoveField(
            model_name='printers',
            name='date',
        ),
        migrations.RemoveField(
            model_name='routers',
            name='date',
        ),
    ]
